"Resource\OptionsSubKeyboard.res"
{
	"Defaults"
	{
		"ControlName"		"Button"
		"fieldName"		"Defaults"
		"xpos"		"12"
		"ypos"		"342"
		"wide"		"105"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"labelText"		"#GameUI_UseDefaults"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"Defaults"
		"default"		"0"
	}
	"listpanel_keybindlist"
	{
		"ControlName"		"ListPanel"
		"fieldName"		"listpanel_keybindlist"
		"xpos"		"12"
		"ypos"		"12"
		"wide"		"560"
		"tall"		"320"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
	}
	"ChangeKeyButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ChangeKeyButton"
		"xpos"		"310"
		"ypos"		"342"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"3"
		"labelText"		"#GameUI_SetNewKey"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"ChangeKey"
		"default"		"1"
	}
	"ClearKeyButton"
	{
		"ControlName"		"Button"
		"fieldName"		"ClearKeyButton"
		"xpos"		"408"
		"ypos"		"342"
		"wide"		"84"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"labelText"		"#GameUI_ClearKey"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"ClearKey"
		"default"		"0"
	}
}
