cmake_minimum_required(VERSION 3.21)
if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    project(NextClientLifeStats LANGUAGES CXX)
endif()
find_package(taocpp-json CONFIG REQUIRED)
add_library(plugin_life_stats_cpp SHARED life_stats.cpp tracker.cpp)
target_include_directories(plugin_life_stats_cpp PRIVATE ../../cpp/include)
target_compile_features(plugin_life_stats_cpp PRIVATE cxx_std_23)
target_compile_options(plugin_life_stats_cpp PRIVATE /W4 /WX /EHsc /utf-8)
target_link_libraries(plugin_life_stats_cpp PRIVATE taocpp::json)
set_target_properties(plugin_life_stats_cpp PROPERTIES OUTPUT_NAME life_stats MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

if(NOT CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    set_target_properties(plugin_life_stats_cpp PROPERTIES OUTPUT_NAME life_stats_cpp)
endif()
