#pragma once
#define LAUNCHER_VERSION "2.5.0 ("  __DATE__ " " __TIME__ ")"
#define NEXT_CLIENT_BUILD_VERSION "2.5.0"
#define NEXT_CLIENT_BUILD_VERSION_MAJOR 2
#define NEXT_CLIENT_BUILD_VERSION_MINOR 5
#define NEXT_CLIENT_BUILD_VERSION_PATCH 0
#define NEXT_CLIENT_BUILD_VERSION_PRERELEASE ""
