#pragma once
#define LAUNCHER_VERSION "1.2.4 ("  __DATE__ " " __TIME__ ")"
#define NEXT_CLIENT_BUILD_VERSION "2.4.0-beta.4"
#define NEXT_CLIENT_BUILD_VERSION_MAJOR 2
#define NEXT_CLIENT_BUILD_VERSION_MINOR 4
#define NEXT_CLIENT_BUILD_VERSION_PATCH 0
